import type { Prisma } from '../../../db/prisma/generated/client';
import * as z from 'zod';
import { VerificationWhereInputObjectSchema as VerificationWhereInputObjectSchema } from './objects/VerificationWhereInput.schema';
import { VerificationOrderByWithAggregationInputObjectSchema as VerificationOrderByWithAggregationInputObjectSchema } from './objects/VerificationOrderByWithAggregationInput.schema';
import { VerificationScalarWhereWithAggregatesInputObjectSchema as VerificationScalarWhereWithAggregatesInputObjectSchema } from './objects/VerificationScalarWhereWithAggregatesInput.schema';
import { VerificationScalarFieldEnumSchema } from './enums/VerificationScalarFieldEnum.schema';
import { VerificationCountAggregateInputObjectSchema as VerificationCountAggregateInputObjectSchema } from './objects/VerificationCountAggregateInput.schema';
import { VerificationMinAggregateInputObjectSchema as VerificationMinAggregateInputObjectSchema } from './objects/VerificationMinAggregateInput.schema';
import { VerificationMaxAggregateInputObjectSchema as VerificationMaxAggregateInputObjectSchema } from './objects/VerificationMaxAggregateInput.schema';
import { VerificationAvgAggregateInputObjectSchema as VerificationAvgAggregateInputObjectSchema } from './objects/VerificationAvgAggregateInput.schema';
import { VerificationSumAggregateInputObjectSchema as VerificationSumAggregateInputObjectSchema } from './objects/VerificationSumAggregateInput.schema';

export const VerificationGroupBySchema: z.ZodType<Prisma.VerificationGroupByArgs> = z.object({ where: VerificationWhereInputObjectSchema.optional(), orderBy: z.union([VerificationOrderByWithAggregationInputObjectSchema, VerificationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: VerificationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(VerificationScalarFieldEnumSchema), _count: z.union([ z.literal(true), VerificationCountAggregateInputObjectSchema ]).optional(), _min: VerificationMinAggregateInputObjectSchema.optional(), _max: VerificationMaxAggregateInputObjectSchema.optional(), _avg: VerificationAvgAggregateInputObjectSchema.optional(), _sum: VerificationSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.VerificationGroupByArgs>;

export const VerificationGroupByZodSchema = z.object({ where: VerificationWhereInputObjectSchema.optional(), orderBy: z.union([VerificationOrderByWithAggregationInputObjectSchema, VerificationOrderByWithAggregationInputObjectSchema.array()]).optional(), having: VerificationScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(VerificationScalarFieldEnumSchema), _count: z.union([ z.literal(true), VerificationCountAggregateInputObjectSchema ]).optional(), _min: VerificationMinAggregateInputObjectSchema.optional(), _max: VerificationMaxAggregateInputObjectSchema.optional(), _avg: VerificationAvgAggregateInputObjectSchema.optional(), _sum: VerificationSumAggregateInputObjectSchema.optional() }).strict();