import type { Prisma } from '../../../db/prisma/generated/client';
import * as z from 'zod';
import { ChatroomWhereInputObjectSchema as ChatroomWhereInputObjectSchema } from './objects/ChatroomWhereInput.schema';
import { ChatroomOrderByWithAggregationInputObjectSchema as ChatroomOrderByWithAggregationInputObjectSchema } from './objects/ChatroomOrderByWithAggregationInput.schema';
import { ChatroomScalarWhereWithAggregatesInputObjectSchema as ChatroomScalarWhereWithAggregatesInputObjectSchema } from './objects/ChatroomScalarWhereWithAggregatesInput.schema';
import { ChatroomScalarFieldEnumSchema } from './enums/ChatroomScalarFieldEnum.schema';
import { ChatroomCountAggregateInputObjectSchema as ChatroomCountAggregateInputObjectSchema } from './objects/ChatroomCountAggregateInput.schema';
import { ChatroomMinAggregateInputObjectSchema as ChatroomMinAggregateInputObjectSchema } from './objects/ChatroomMinAggregateInput.schema';
import { ChatroomMaxAggregateInputObjectSchema as ChatroomMaxAggregateInputObjectSchema } from './objects/ChatroomMaxAggregateInput.schema';
import { ChatroomAvgAggregateInputObjectSchema as ChatroomAvgAggregateInputObjectSchema } from './objects/ChatroomAvgAggregateInput.schema';
import { ChatroomSumAggregateInputObjectSchema as ChatroomSumAggregateInputObjectSchema } from './objects/ChatroomSumAggregateInput.schema';

export const ChatroomGroupBySchema: z.ZodType<Prisma.ChatroomGroupByArgs> = z.object({ where: ChatroomWhereInputObjectSchema.optional(), orderBy: z.union([ChatroomOrderByWithAggregationInputObjectSchema, ChatroomOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ChatroomScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ChatroomScalarFieldEnumSchema), _count: z.union([ z.literal(true), ChatroomCountAggregateInputObjectSchema ]).optional(), _min: ChatroomMinAggregateInputObjectSchema.optional(), _max: ChatroomMaxAggregateInputObjectSchema.optional(), _avg: ChatroomAvgAggregateInputObjectSchema.optional(), _sum: ChatroomSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ChatroomGroupByArgs>;

export const ChatroomGroupByZodSchema = z.object({ where: ChatroomWhereInputObjectSchema.optional(), orderBy: z.union([ChatroomOrderByWithAggregationInputObjectSchema, ChatroomOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ChatroomScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ChatroomScalarFieldEnumSchema), _count: z.union([ z.literal(true), ChatroomCountAggregateInputObjectSchema ]).optional(), _min: ChatroomMinAggregateInputObjectSchema.optional(), _max: ChatroomMaxAggregateInputObjectSchema.optional(), _avg: ChatroomAvgAggregateInputObjectSchema.optional(), _sum: ChatroomSumAggregateInputObjectSchema.optional() }).strict();