/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSpaceIdRouteRouteImport } from './routes/_auth/$spaceId/route'
import { Route as AuthThemesEditIndexRouteImport } from './routes/_auth/themes/edit/index'
import { Route as AuthSpaceIdChannelidIndexRouteImport } from './routes/_auth/$spaceId/$channelid/index'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSpaceIdRouteRoute = AuthSpaceIdRouteRouteImport.update({
  id: '/$spaceId',
  path: '/$spaceId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthThemesEditIndexRoute = AuthThemesEditIndexRouteImport.update({
  id: '/themes/edit/',
  path: '/themes/edit/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSpaceIdChannelidIndexRoute =
  AuthSpaceIdChannelidIndexRouteImport.update({
    id: '/$channelid/',
    path: '/$channelid/',
    getParentRoute: () => AuthSpaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/success': typeof SuccessRoute
  '/$spaceId': typeof AuthSpaceIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/$spaceId/$channelid/': typeof AuthSpaceIdChannelidIndexRoute
  '/themes/edit/': typeof AuthThemesEditIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/success': typeof SuccessRoute
  '/$spaceId': typeof AuthSpaceIdRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/': typeof AuthIndexRoute
  '/$spaceId/$channelid': typeof AuthSpaceIdChannelidIndexRoute
  '/themes/edit': typeof AuthThemesEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/success': typeof SuccessRoute
  '/_auth/$spaceId': typeof AuthSpaceIdRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/$spaceId/$channelid/': typeof AuthSpaceIdChannelidIndexRoute
  '/_auth/themes/edit/': typeof AuthThemesEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/design'
    | '/success'
    | '/$spaceId'
    | '/login'
    | '/$spaceId/$channelid/'
    | '/themes/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/dashboard'
    | '/design'
    | '/success'
    | '/$spaceId'
    | '/login'
    | '/'
    | '/$spaceId/$channelid'
    | '/themes/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/chat'
    | '/dashboard'
    | '/design'
    | '/success'
    | '/_auth/$spaceId'
    | '/_auth/login'
    | '/_auth/'
    | '/_auth/$spaceId/$channelid/'
    | '/_auth/themes/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/$spaceId': {
      id: '/_auth/$spaceId'
      path: '/$spaceId'
      fullPath: '/$spaceId'
      preLoaderRoute: typeof AuthSpaceIdRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/themes/edit/': {
      id: '/_auth/themes/edit/'
      path: '/themes/edit'
      fullPath: '/themes/edit/'
      preLoaderRoute: typeof AuthThemesEditIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/$spaceId/$channelid/': {
      id: '/_auth/$spaceId/$channelid/'
      path: '/$channelid'
      fullPath: '/$spaceId/$channelid/'
      preLoaderRoute: typeof AuthSpaceIdChannelidIndexRouteImport
      parentRoute: typeof AuthSpaceIdRouteRoute
    }
  }
}

interface AuthSpaceIdRouteRouteChildren {
  AuthSpaceIdChannelidIndexRoute: typeof AuthSpaceIdChannelidIndexRoute
}

const AuthSpaceIdRouteRouteChildren: AuthSpaceIdRouteRouteChildren = {
  AuthSpaceIdChannelidIndexRoute: AuthSpaceIdChannelidIndexRoute,
}

const AuthSpaceIdRouteRouteWithChildren =
  AuthSpaceIdRouteRoute._addFileChildren(AuthSpaceIdRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSpaceIdRouteRoute: typeof AuthSpaceIdRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthThemesEditIndexRoute: typeof AuthThemesEditIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSpaceIdRouteRoute: AuthSpaceIdRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthThemesEditIndexRoute: AuthThemesEditIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
