/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthBBoardSlugRouteRouteImport } from './routes/_auth/b.$boardSlug/route'
import { Route as AuthThemesEditIndexRouteImport } from './routes/_auth/themes/edit/index'
import { Route as AuthBBoardSlugIndexRouteImport } from './routes/_auth/b.$boardSlug/index'
import { Route as AuthBBoardSlugItemSlugIndexRouteImport } from './routes/_auth/b.$boardSlug/$itemSlug/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBBoardSlugRouteRoute = AuthBBoardSlugRouteRouteImport.update({
  id: '/b/$boardSlug',
  path: '/b/$boardSlug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthThemesEditIndexRoute = AuthThemesEditIndexRouteImport.update({
  id: '/themes/edit/',
  path: '/themes/edit/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBBoardSlugIndexRoute = AuthBBoardSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthBBoardSlugRouteRoute,
} as any)
const AuthBBoardSlugItemSlugIndexRoute =
  AuthBBoardSlugItemSlugIndexRouteImport.update({
    id: '/$itemSlug/',
    path: '/$itemSlug/',
    getParentRoute: () => AuthBBoardSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof AuthLoginRoute
  '/b/$boardSlug': typeof AuthBBoardSlugRouteRouteWithChildren
  '/b/$boardSlug/': typeof AuthBBoardSlugIndexRoute
  '/themes/edit/': typeof AuthThemesEditIndexRoute
  '/b/$boardSlug/$itemSlug/': typeof AuthBBoardSlugItemSlugIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/': typeof AuthIndexRoute
  '/b/$boardSlug': typeof AuthBBoardSlugIndexRoute
  '/themes/edit': typeof AuthThemesEditIndexRoute
  '/b/$boardSlug/$itemSlug': typeof AuthBBoardSlugItemSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/b/$boardSlug': typeof AuthBBoardSlugRouteRouteWithChildren
  '/_auth/b/$boardSlug/': typeof AuthBBoardSlugIndexRoute
  '/_auth/themes/edit/': typeof AuthThemesEditIndexRoute
  '/_auth/b/$boardSlug/$itemSlug/': typeof AuthBBoardSlugItemSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/b/$boardSlug'
    | '/b/$boardSlug/'
    | '/themes/edit/'
    | '/b/$boardSlug/$itemSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/b/$boardSlug'
    | '/themes/edit'
    | '/b/$boardSlug/$itemSlug'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/'
    | '/_auth/b/$boardSlug'
    | '/_auth/b/$boardSlug/'
    | '/_auth/themes/edit/'
    | '/_auth/b/$boardSlug/$itemSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/b/$boardSlug': {
      id: '/_auth/b/$boardSlug'
      path: '/b/$boardSlug'
      fullPath: '/b/$boardSlug'
      preLoaderRoute: typeof AuthBBoardSlugRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/themes/edit/': {
      id: '/_auth/themes/edit/'
      path: '/themes/edit'
      fullPath: '/themes/edit/'
      preLoaderRoute: typeof AuthThemesEditIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/b/$boardSlug/': {
      id: '/_auth/b/$boardSlug/'
      path: '/'
      fullPath: '/b/$boardSlug/'
      preLoaderRoute: typeof AuthBBoardSlugIndexRouteImport
      parentRoute: typeof AuthBBoardSlugRouteRoute
    }
    '/_auth/b/$boardSlug/$itemSlug/': {
      id: '/_auth/b/$boardSlug/$itemSlug/'
      path: '/$itemSlug'
      fullPath: '/b/$boardSlug/$itemSlug/'
      preLoaderRoute: typeof AuthBBoardSlugItemSlugIndexRouteImport
      parentRoute: typeof AuthBBoardSlugRouteRoute
    }
  }
}

interface AuthBBoardSlugRouteRouteChildren {
  AuthBBoardSlugIndexRoute: typeof AuthBBoardSlugIndexRoute
  AuthBBoardSlugItemSlugIndexRoute: typeof AuthBBoardSlugItemSlugIndexRoute
}

const AuthBBoardSlugRouteRouteChildren: AuthBBoardSlugRouteRouteChildren = {
  AuthBBoardSlugIndexRoute: AuthBBoardSlugIndexRoute,
  AuthBBoardSlugItemSlugIndexRoute: AuthBBoardSlugItemSlugIndexRoute,
}

const AuthBBoardSlugRouteRouteWithChildren =
  AuthBBoardSlugRouteRoute._addFileChildren(AuthBBoardSlugRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthBBoardSlugRouteRoute: typeof AuthBBoardSlugRouteRouteWithChildren
  AuthThemesEditIndexRoute: typeof AuthThemesEditIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthBBoardSlugRouteRoute: AuthBBoardSlugRouteRouteWithChildren,
  AuthThemesEditIndexRoute: AuthThemesEditIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
