/**
 * Conceptual — adapter boundary.
 *
 * Internal Butter model ids stay stable.
 * `tables` maps those ids → Prisma model / table names in *your* schema.
 * That is storage mapping, not the public API alias.
 */

import { PrismaAdapter } from "../_aspirational"
import { prisma } from "./db"

/**
 * Example Prisma schema (not generated by Butter):
 *
 *   model Contributor {
 *     id    String @id
 *     email String @unique
 *     // …
 *     @@map("users")              // physical table can be anything
 *   }
 *
 *   model Publication {
 *     id   String @id
 *     name String
 *     @@map("organizations")
 *   }
 *
 * Public Butter model alias "contributor" / "publication" is independent
 * of both the Prisma model name and the @@map table name.
 * The adapter bridges: Butter internal id → Prisma delegate.
 */
export const adapter = PrismaAdapter(prisma, {
  tables: {
    // butter internal model id → Prisma client key
    user: "contributor", // prisma.contributor
    session: "session",
    account: "account",
    verification: "verification",
    organization: "publication", // prisma.publication
    member: "staff",
  },
})
